name: CI 

on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: asia-east2-a
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    steps:
      # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      # Deploy
      - name: 'run deploy.sh'
        run: 'cd /var/www/ezactive.com/public_html/test-cicd && sudo sh deploy.sh'
