name: CI 

on:
  push:
    branches: [ main ]
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  RUN_REGION: asia-east2-a
  SA_KEY_JSON: ${{ secrets.GCP_SA_KEY_JSON }}
jobs:
  deploy:
    name: Deploy to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Setup gcloud CLI
      # - id: 'auth'
      - name: Login
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          # credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: 'pwd'
        run: 'pwd'

      - name: 'whoami'
        run: 'whoami'

      # Deploy
      - name: 'run deploy.sh'
        run: 'cd /var/www/ezactive.com/public_html/test-cicd && sudo sh deploy.sh'
